DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
    MEMBER_NO NUMBER,
    ID VARCHAR2(30) NOT NULL,
    PW VARCHAR2(64) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20),
    EMAIL VARCHAR2(50),
    PHONE1 VARCHAR2(13) NOT NULL,
    PHONE2 VARCHAR2(13) NOT NULL,
    MANAGE NUMBER(1),
    STATUS NUMBER(1),
    REGDATE DATE
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_NO);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_ID_UQ UNIQUE(ID);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_EMAIL_UQ UNIQUE(EMAIL);
