DROP TABLE CONTACT;
DROP SEQUENCE CONTACT_SEQ;

CREATE TABLE CONTACT
(
    NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(30),
    TEL VARCHAR2(20),
    ADDR VARCHAR2(200),
    EMAIL VARCHAR2(100),
    NOTE VARCHAR2(300)
);

CREATE SEQUENCE CONTACT_SEQ
  START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;