DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;

CREATE TABLE BOARD
(
    NO NUMBER PRIMARY KEY,
    WRITER VARCHAR2(32),
    TITLE VARCHAR2(100),
    CONTENT VARCHAR2(100),
    FILENAME VARCHAR2(300),
    POSTDATE DATE
);

CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;